### ISSUE TITLE
libjnffmpeg.so can not compile

### ISSUE THREAD

**Issue by mandian-lx** [jitsi/jitsi-lgpl-dependencies#2]
I am trying to compile jitsi-lgpl-dependencies form sources but I got some problems in compiling libjnffmpeg.so native library.

Here the commands I used:

export JAVA_HOME=/usr/lib/jvm/java
ant -v ffmpeg -Dffmpeg=/usr/include/ -Dlame="" -Dvoamrwbenc="" -Dx264="" -DLIBAV=""

Here the result:

[ffmpeg.txt](https://github.com/jitsi/jitsi-lgpl-dependencies/files/321704/ffmpeg.txt)

**Comment by ibauersachs** [comment]
The whole build process has been revamped with the switch to OpenH264. Please open a new issue if you encounter new problems (or better yet, a pull request that fixes it).
