### ISSUE TITLE
Duplicate native libraries

### ISSUE THREAD

**Issue by uniqueid001** [jitsi/jitsi-lgpl-dependencies#3]
This project contains duplicate copies of the .so/.dll/.dynlib files.  One copy is in `src/main/resources/`, the other is in `lib/native/`.  Some parts of the ant, and maven, builds use one location and some parts use the other.

**Comment by ibauersachs** [comment]
The duplicates were removed in 48c18c8289390dd97878627550a56dc8799d5fb5.
